### ISSUE TITLE
Json error in couchpotato 

### ISSUE THREAD

**Issue by nzbmanager** [nzbmanager/nzbmanager_issues#15]
When trying to access cp there's a json error
## 
## Device info:

<table>
<tr><td>App version</td><td>6.0.02</td></tr>
<tr><td>App version code</td><td>110</td></tr>
<tr><td>Android build version</td><td>C233B112</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>KANGVIP SLIM B211</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWGemini</td></tr>
<tr><td>Device model</td><td>GEM-703L</td></tr>
<tr><td>Device product name</td><td>GEM-703L</td></tr>
<tr><td>Device hardware name</td><td>hi3635</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by nzbmanager** [comment]
I need the exact error

**Comment by travisbaker** [comment]
The error is a Jain parse error. Cannot conversation your string to jsonObject. I get this when I navigate to the couch potato tab. Must have been an API change recently.
